### ISSUE TITLE
on sending message to a runtime on which NO LISTENER added

### ISSUE THREAD

**Issue by otiai10** [otiai10/chomex#36]
```
Error in event handler for (unknown): TypeError: Cannot read property 'status' of undefined
    at TargettedClient../node_modules/chomex/lib/Client/index.js.Client._finally (chrome-extension://mbhfjahbokpmoabjfinclaingicjddpc/dest/js/background.js:246:40)
    at defaultCallback (chrome-extension://mbhfjahbokpmoabjfinclaingicjddpc/dest/js/background.js:223:23)
```

client raises error

**Comment by otiai10** [comment]
https://github.com/otiai10/chomex/blob/master/src/Client/index.ts#L143

**Comment by otiai10** [comment]
```
Error in event handler for (unknown): TypeError: Cannot read property 'status' of undefined
    at TargettedClient.Client._finally (chrome-extension://efldimenahbinjbadljegjojlimebejd/dest/js/background.js:306:40)
    at defaultCallback (chrome-extension://efldimenahbinjbadljegjojlimebejd/dest/js/background.js:283:23)
```

Also when client DOESN'T send any response.
